name: autofix.ci

on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: actions/checkout@v5
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run lint --fix
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
