name: CI
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: pnpm install
      - run: pnpm build
      - run: node -v
      - run: pnpm lint
      - run: pnpm test
