name: pkg.pr.new
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - run: pnpm install
      - run: pnpm build
      - run: pnpm pkg-pr-new publish
